basePath: /api/v1
definitions:
  category.categoryOutput:
    properties:
      category:
        example: electronics
        type: string
      created_at:
        example: 1709885754000
        type: integer
      updated_at:
        example: 1709885754000
        type: integer
    type: object
  category.createCategoryInput:
    properties:
      name:
        example: electronics
        maxLength: 32
        type: string
    required:
    - name
    type: object
  category.updateCategoryInput:
    properties:
      new_name:
        example: electronics
        maxLength: 32
        type: string
    required:
    - new_name
    type: object
  util.ErrorModel:
    properties:
      message:
        example: something went wrong
        type: string
      status:
        example: 400
        type: integer
    type: object
host: localhost:4000
info:
  contact: {}
  description: The comprehensive list of all Money Tracker APIs
  title: Money Tracker APIs
  version: "1.0"
paths:
  /expenditure/category:
    get:
      description: Get all expenditure categories, this API will return an error if
        none have been created.
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorModel'
      summary: Get all expenditure categories
      tags:
      - expenditure category
    post:
      description: Create a new expenditure category, this API will return an error
        if the category has already been created.
      parameters:
      - description: json
        in: body
        name: request-body
        required: true
        schema:
          $ref: '#/definitions/category.createCategoryInput'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/category.categoryOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorModel'
      summary: Create a new expenditure category
      tags:
      - expenditure category
  /expenditure/category/{category-name}:
    delete:
      description: Delete an expenditure category's, this API will return an error
        if the category does not exist.
      parameters:
      - description: Category Name
        in: path
        maxLength: 32
        name: category-name
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/category.categoryOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorModel'
      summary: Delete an expenditure category's
      tags:
      - expenditure category
    put:
      description: Update an expenditure category's name, this API will return an
        error if the category does not exist.
      parameters:
      - description: Category Name
        in: path
        maxLength: 32
        name: category-name
        required: true
        type: string
      - description: json
        in: body
        name: request-body
        required: true
        schema:
          $ref: '#/definitions/category.updateCategoryInput'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/category.categoryOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorModel'
      summary: Update an expenditure category's name
      tags:
      - expenditure category
swagger: "2.0"
