// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Expenditure struct {
	ID         uuid.UUID `json:"id"`
	Paisa      int32     `json:"paisa"`
	Categoryid uuid.UUID `json:"categoryid"`
	Createdat  time.Time `json:"createdat"`
	Updatedat  time.Time `json:"updatedat"`
}

type Expenditurecategory struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Createdat time.Time `json:"createdat"`
	Updatedat time.Time `json:"updatedat"`
}
